services:
  - type: static
    name: motozone-ek
    env: static
    buildCommand: npm install; npm run build
    publishDir: dist
    routes:
      - type: rewrite
        source: /((?!\.).*)$
        destination: /index.html
